module Bidi2pdf
  class ChromedriverManager
    @port: untyped

    @headless: untyped

    @session: untyped

    @started: untyped

    @chrome_args: untyped

    @shutdown_mutex: untyped

    @pid: untyped

    include Chromedriver::Binary::Platform

    attr_reader port: untyped

    attr_reader pid: untyped

    attr_reader started: untyped

    attr_reader headless: untyped

    attr_reader chrome_args: untyped

    attr_reader shutdown_mutex: untyped

    attr_accessor reader_thread: untyped

    def initialize: (?port: ::Integer, ?headless: bool, ?chrome_args: untyped) -> void

    def start: () -> untyped

    def session: () -> (nil | untyped)

    def session_url: () -> (nil | ::String)

    # rubocop: disable Metrics/AbcSize
    def stop: (?timeout: ::Integer) -> untyped

    private

    def spawn_process: (untyped cmd) -> untyped

    def detect_zombie_processes: (untyped old_childprocesses) -> (nil | untyped)

    def term_zombie_processes: (untyped zombie_processes) -> untyped

    def debug_show_all_children: () -> untyped

    def close_session: () -> untyped

    def term_chromedriver: () -> untyped

    def kill_chromedriver: (?timeout: ::Integer) -> untyped

    def build_cmd: () -> untyped

    def chromedriver_log_level: () -> untyped

    def user_data_dir_arg: () -> (untyped | ::String)

    def process_chrome_args: () -> (::Array[untyped] | untyped)

    def update_chromedriver: () -> untyped

    # rubocop: disable Metrics/AbcSize
    def parse_port_from_output: (untyped io, ?timeout: ::Integer) -> (nil | untyped)

    def process_alive?: (?untyped pid) -> (false | untyped)

    def wait_until_chromedriver_ready: (?timeout: ::Integer) -> (true | untyped)
  end
end
