module Bidi2pdf
  # Represents a launcher for managing browser sessions and executing tasks
  # using the Bidi2pdf library. This class handles the setup and teardown
  # of browser sessions, as well as the execution of tasks within those sessions.
  #
  # @example Launching a session
  #   launcher = Bidi2pdf::Launcher.new(
  #     url: "http://example.com",
  #     inputfile: "input.pdf",
  #     output: "output.pdf",
  #     cookies: [],
  #     headers: {},
  #     auth: nil,
  #     headless: true
  #   )
  #   launcher.launch
  #   launcher.stop
  #
  # @param [String] url The URL to navigate to in the browser session.
  # @param [String] inputfile The path to the input file to be processed.
  # @param [String] output The path to the output file to be generated.
  # @param [Array<Hash>] cookies An array of cookies to set in the browser session.
  # @param [Hash] headers A hash of HTTP headers to include in the browser session.
  # @param [Hash, nil] auth Authentication credentials (e.g., username and password).
  # @param [Boolean] headless Whether to run the browser in headless mode. Defaults to true.
  # @param [Integer] port The port to use for the browser session. Defaults to 0.
  # @param [Boolean] wait_window_loaded Whether to wait for the window to fully load. Defaults to false.
  # @param [Boolean] wait_network_idle Whether to wait for the network to become idle. Defaults to false.
  # @param [Hash] print_options Options for printing the page. Defaults to an empty hash.
  # @param [String, nil] remote_browser_url The URL of a remote browser to connect to. Defaults to nil.
  # @param [Symbol] network_log_format The format for network logs. Defaults to :console.
  class Launcher
    @url: untyped

    @inputfile: untyped

    @port: untyped

    @headless: untyped

    @output: untyped

    @cookies: untyped

    @headers: untyped

    @auth: untyped

    @manager: untyped

    @wait_window_loaded: untyped

    @wait_network_idle: untyped

    @print_options: untyped

    @remote_browser_url: untyped

    @custom_session: untyped

    @network_log_format: untyped

    @chrome_args: untyped

    # rubocop:disable Metrics/ParameterLists
    def initialize: (url: untyped, inputfile: untyped, output: untyped, cookies: untyped, headers: untyped, auth: untyped, ?headless: bool, ?port: ::Integer, ?wait_window_loaded: bool, ?wait_network_idle: bool, ?print_options: ::Hash[untyped, untyped], ?remote_browser_url: untyped?, ?network_log_format: ::Symbol, ?chrome_args: untyped) -> void

    def launch: () -> untyped

    def stop: () -> untyped

    private

    def session: () -> untyped
  end
end
