AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 10


Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

RSpec/InstanceVariable:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: true
  Exclude:
    - 'spec/acceptance/**/*_spec.rb'

RSpec/DescribeClass:
  Enabled: true
  Exclude:
    - 'spec/acceptance/**/*_spec.rb'

plugins:
  - rubocop-rake
  - rubocop-rspec
