name: bidi2pdf
services:
  nginx:
    image: nginx:1.27-bookworm
    ports:
      - "9091:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/htpasswd:/etc/nginx/conf.d/.htpasswd
      - ../spec/fixtures:/var/www/html

  remote-chrome:
    build:
      context: ..
      dockerfile: docker/Dockerfile.chromedriver
    ports:
      - "9092:3000"

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../tmp/reports:/reports
    command: tail -f /dev/null
