module Bidi2pdf
  module Chrome
    module VersionResolver
      def browser_build_version: -> Gem::Version

      def browser_version: -> Gem::Version

      def direct_url_from_api: (_ToS driver_version, String driver_filename) -> String

      def latest_patch_version_for_build: -> String

      def normalize_version: (_ToS version) -> Gem::Version

      private

      def fetch_data: (String json_file) -> String
    end
  end
end
