module Bidi2pdf
  module Bidi
    class AddHeadersInterceptor
      @headers: untyped

      @url_patterns: untyped

      @context: untyped

      include Interceptor

      def self.phases: () -> ::Array[untyped]

      def self.events: () -> ::Array["network.beforeRequestSent"]

      attr_reader headers: untyped

      attr_reader url_patterns: untyped

      attr_reader context: untyped

      def initialize: (headers: untyped, url_patterns: untyped, context: untyped) -> void

      def process_interception: (untyped _event_response, untyped _navigation_id, untyped network_id, untyped _url) -> untyped
    end
  end
end
