module Bidi2pdf
  module Bidi
    class AuthInterceptor
      @url_patterns: untyped

      @context: untyped

      @username: untyped

      @password: untyped

      @network_ids: untyped

      include Interceptor

      def self.phases: () -> ::Array[untyped]

      def self.events: () -> ::Array["network.authRequired"]

      attr_reader headers: untyped

      attr_reader url_patterns: untyped

      attr_reader context: untyped

      attr_reader username: untyped

      attr_reader password: untyped

      attr_reader network_ids: untyped

      def initialize: (username: untyped, password: untyped, url_patterns: untyped, context: untyped) -> void

      def process_interception: (untyped _event_response, untyped navigation_id, untyped network_id, untyped url) -> untyped

      private

      # rubocop:disable Naming/PredicateMethod
      def handled_bad_credentials: (untyped navigation_id, untyped network_id, untyped url) -> (false | true)
    end
  end
end
