module Bidi2pdf
  module Bidi
    class CommandManager
      self.@id: untyped

      @socket: untyped

      @pending_responses: untyped

      def self.initialize_counter: () -> untyped

      def self.next_id: () -> untyped

      def initialize: (untyped socket) -> void

      def send_cmd: (untyped cmd, ?result_queue: untyped?) -> untyped

      def send_cmd_and_wait: (untyped cmd, ?timeout: untyped) { (?) -> untyped } -> untyped

      def handle_response: (untyped data) -> untyped

      private

      def init_queue_for: (untyped id, untyped result_queue) -> untyped

      def next_id: () -> untyped
    end
  end
end
