module Bidi2pdf
  module Bidi
    class EventManager
      @listeners: untyped

      @type: untyped

      Listener: untyped

      attr_reader type: untyped

      def initialize: (untyped type) -> void

      def on: (*untyped event_names) { (?) -> untyped } -> untyped

      def off: (untyped event_name, untyped listener) -> untyped

      def dispatch: (untyped event_name, *untyped args) -> untyped

      def clear: (?untyped? event_name) -> untyped

      private

      def log_msg: (untyped prefix, untyped data) -> untyped

      # rubocop: disable all
      def truncate_large_values: (untyped org, ?::Integer max_length, ?::Integer max_depth, ?::Integer current_depth) -> ("...(too deep)..." | untyped)
    end
  end
end
