module Bidi2pdf
  module Bidi
    class EventManager
      class Listener
        attr_reader block: untyped
        attr_reader id: String

        def initialize: (untyped block, ?String id) -> void

        def call: (*untyped args) -> untyped

        def ==: (untyped other) -> bool

        def eql?: (untyped other) -> bool

        def hash: () -> Integer
      end

      @listeners: untyped
      @type: untyped

      attr_reader type: untyped

      def initialize: (untyped type) -> void

      def on: (*untyped event_names, &untyped block) -> Listener

      def off: (untyped event_name, Listener listener) -> void

      def dispatch: (untyped event_name, *untyped args) -> void

      def clear: (?untyped event_name) -> void
    end
  end
end