module Bidi2pdf
  module Bidi
    class LoggerEvents
      @context_id: untyped

      @browser_console_logger: untyped

      attr_reader context_id: untyped

      attr_reader browser_console_logger: untyped

      def initialize: (untyped context_id) -> void

      def handle_event: (untyped data) -> untyped

      def handle_response: (untyped _method, untyped event) -> untyped

      def resolve_log_level: (untyped js_level) -> untyped
    end
  end
end
