module Bidi2pdf
  module Bidi
    class UserContext
      @browser: Bidi2pdf::Bidi::Browser
      @context_id: String
      @session_id: String?
      @event_manager: Bidi2pdf::Bidi::EventManager?
      @network_events: Bidi2pdf::Bidi::NetworkEvents?
      @closed: bool

      attr_reader context_id: String
      attr_reader browser: Bidi2pdf::Bidi::Browser
      attr_reader session_id: String?

      def initialize: (
          browser: Bidi2pdf::Bidi::Browser,
          context_id: String,
          ?session_id: String?
        ) -> void

      def create_session: () -> String

      def attach_session: (session_id: String) -> String

      def execute_command: [T] (String method, ?Hash[Symbol, untyped] params) -> T

      def navigate_to: (String url) -> void

      def evaluate: [T] (String script) -> T

      def wait_for_load: (?timeout: Integer?) -> void

      def network_events: () -> Bidi2pdf::Bidi::NetworkEvents

      def capture_screenshot: (?path: String?) -> String

      def print_to_pdf: (?Hash[Symbol, untyped] parameters) -> String

      def close: () -> void

      def closed?: () -> bool

      private

      def ensure_open: () -> void

      def setup_event_listeners: () -> void
    end
  end
end