module Bidi2pdf
  module Bidi
    # Represents a user context for managing browser interactions and cookies
    # using the Bidi2pdf library. This class provides methods for creating
    # user contexts, setting cookies, and creating browser windows.
    #
    # @example Creating a user context
    #   user_context = Bidi2pdf::Bidi::UserContext.new(client)
    #
    # @example Setting a cookie
    #   user_context.set_cookie(
    #     name: "session",
    #     value: "abc123",
    #     domain: "example.com",
    #     source_origin: "http://example.com"
    #   )
    #
    # @example Creating a browser window
    #   browser_window = user_context.create_browser_window
    #
    # @param [Object] client The WebSocket client for communication.
    class UserContext
      @client: untyped

      @context_id: untyped

      # @return [Object] The WebSocket client.
      attr_reader client: untyped

      # Initializes a new user context.
      #
      # @param [Object] client The WebSocket client for communication.
      def initialize: (untyped client) -> void

      # Retrieves the user context ID, creating it if it does not exist.
      #
      # @return [String] The user context ID.
      # @raise [RuntimeError] If an error occurs while creating the user context.
      def context_id: () -> untyped

      # Sets a cookie in the user context.
      #
      # @param [String] name The name of the cookie.
      # @param [String] value The value of the cookie.
      # @param [String] domain The domain for the cookie.
      # @param [String] source_origin The source origin for the cookie.
      # @param [String] path The path for the cookie. Defaults to "/".
      # @param [Boolean] secure Whether the cookie is secure. Defaults to true.
      # @param [Boolean] http_only Whether the cookie is HTTP-only. Defaults to false.
      # @param [String] same_site The SameSite attribute for the cookie. Defaults to "strict".
      # @param [Integer] ttl The time-to-live for the cookie in seconds. Defaults to 30.
      def set_cookie: (name: untyped, value: untyped, domain: untyped, source_origin: untyped, ?path: ::String, ?secure: bool, ?http_only: bool, ?same_site: ::String, ?ttl: ::Integer) -> untyped

      # Creates a new browser window in the user context.
      #
      # @return [BrowserTab] The newly created browser tab.
      def create_browser_window: () -> untyped

      # Closes the user context.
      #
      # This method removes the user context from the browser, effectively cleaning up
      # any associated resources. If the user context does not exist, the method does nothing.
      #
      # @return [nil]
      # @raise [RuntimeError] If an error occurs while removing the user context.
      def close: () -> (nil | untyped)
    end
  end
end
