module Bidi2pdf
  module Bidi
    class WebSocketDispatcher
      @socket: untyped

      @socket_events: untyped

      @session_events: untyped

      attr_reader socket_events: untyped

      attr_reader session_events: untyped

      def initialize: (untyped socket) -> void

      def start_listening: () -> untyped

      def on_message: () { (?) -> untyped } -> untyped

      def on_event: (*untyped event_names) { (?) -> untyped } -> untyped

      def on_open: () { (?) -> untyped } -> untyped

      def on_close: () { (?) -> untyped } -> untyped

      def on_error: () { (?) -> untyped } -> untyped

      def remove_message_listener: (untyped block) -> untyped

      def remove_event_listener: (untyped name, untyped listener) -> untyped

      def remove_open_listener: (untyped listener) -> untyped

      def remove_close_listener: (untyped listener) -> untyped

      def remove_error_listener: (untyped listener) -> untyped

      private

      def setup_message_handler: () -> untyped

      def setup_connection_lifecycle_handlers: () -> untyped
    end
  end
end
