module Bidi2pdf
  module Bidi
    module Commands
      class AddIntercept
        @context: untyped

        @phases: untyped

        @url_patterns: untyped

        include Base

        BEFORE_REQUEST: "beforeRequestSent"

        RESPONSE_STARTED: "responseStarted"

        AUTH_REQUIRED: "authRequired"

        def initialize: (context: untyped, phases: untyped, url_patterns: untyped) -> void

        def method_name: () -> "network.addIntercept"

        def params: () -> untyped

        def validate_phases!: () -> untyped
      end
    end
  end
end
