module Bidi2pdf
  module Bidi
    module Commands
      class BrowsingContextPrint
        @context: untyped

        @print_options: untyped

        include Base

        def initialize: (context: untyped, print_options: untyped) -> void

        def params: () -> untyped

        def method_name: () -> "browsingContext.print"
      end
    end
  end
end
