module Bidi2pdf
  module Bidi
    module Commands
      class BrowsingContextClose
        @context: untyped

        include Base

        def initialize: (context: untyped) -> void

        def params: () -> { context: untyped }

        def method_name: () -> "browsingContext.close"
      end
    end
  end
end
