module Bidi2pdf
  module Bidi
    module Commands
      class CancelAuth
        @request: untyped

        include Base

        def initialize: (request: untyped) -> void

        def params: () -> { request: untyped, action: "cancel" }

        def method_name: () -> "network.continueWithAuth"
      end
    end
  end
end
