module Bidi2pdf
  module Bidi
    module Commands
      class CreateWindow
        @user_context_id: untyped

        @reference_context: untyped

        @background: untyped

        include Base

        def initialize: (?user_context_id: untyped?, ?reference_context: untyped?, ?background: bool) -> void

        def method_name: () -> "browsingContext.create"

        def params: () -> untyped

        def type: () -> "window"
      end
    end
  end
end
