module Bidi2pdf
  module Bidi
    module Commands
      class NetworkContinue
        @headers: untyped

        @request: untyped

        include Base

        attr_reader request: untyped

        attr_reader headers: untyped

        def initialize: (request: untyped, headers: untyped) -> void
      end
    end
  end
end
