module Bidi2pdf
  module Bidi
    module Commands
      class ProvideCredentials
        include Commands::Base

        def initialize: (
            request: String,
            username: String,
            password: String
          ) -> void
      end
    end
  end
end
