module Bidi2pdf
  module Bidi
    module Commands
      class SetTabCookie
        self.@time_provider: untyped

        @name: untyped

        @value: untyped

        @domain: untyped

        @path: untyped

        @secure: untyped

        @http_only: untyped

        @same_site: untyped

        @ttl: untyped

        @browsing_context_id: untyped

        include Base

        attr_writer self.time_provider: untyped

        def self.time_provider: () -> untyped

        attr_reader name: untyped

        attr_reader value: untyped

        attr_reader domain: untyped

        attr_reader path: untyped

        attr_reader secure: untyped

        attr_reader http_only: untyped

        attr_reader same_site: untyped

        attr_reader ttl: untyped

        attr_reader browsing_context_id: untyped

        def initialize: (name: untyped, value: untyped, domain: untyped, browsing_context_id: untyped, ?path: ::String, ?secure: bool, ?http_only: bool, ?same_site: ::String, ?ttl: ::Integer) -> void

        def expiry: () -> untyped

        def method_name: () -> "storage.setCookie"

        def params: () -> untyped
      end
    end
  end
end
