module Bidi2pdf
  module Bidi
    module Commands
      class SetUsercontextCookie < SetTabCookie
        @user_context_id: untyped

        @source_origin: untyped

        include Base

        attr_reader user_context_id: untyped

        attr_reader source_origin: untyped

        def initialize: (name: untyped, value: untyped, domain: untyped, user_context_id: untyped, source_origin: untyped, ?path: ::String, ?secure: bool, ?http_only: bool, ?same_site: ::String, ?ttl: ::Integer) -> void

        def expiry: () -> untyped

        def method_name: () -> "storage.setCookie"

        def params: () -> untyped
      end
    end
  end
end
